services:
  pgdatabase:
    image: postgres:13 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data_2:/var/lib/postgresql/data:rw" #Created new folder for the mapping
    ports:
      - "5432:5432"
  # Including pgadmin image to verification
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"      
    ports:
      - "8082:80" # "8080:80" is already allocated and we we will a port error. Hence we use port 8082
  